### ISSUE TITLE
malloc check

### ISSUE THREAD

**Issue by atticus-sullivan** [chiyokolinux/kawa#2]
Just a small hint, normally after using malloc one should check if the returned pointer was the nullpointer
(to prevent crashes when later the nullpointer is dereferenced).

**Comment by jonasjaguar** [comment]
Fix planned for the next few days

**Comment by jonasjaguar** [comment]
c7cee3430f97f585f7f2d650d2bf8bd571f7d159
f584089df907ef6fbe880e0afeff03208253e1df
0dc3eee970789a5da657b160530ab1a91c079451

**Comment by jonasjaguar** [comment]
Command to check for unfixed files: `grep -nHPr 'malloc.*(?<!malloc_fail\(\);)$' .`

**Comment by jonasjaguar** [comment]
b8879f4f3b1bb60b3f370c7d081fdb7a8dfbb09a
4cabdd690ab857d0aaf0da183caa036005e7ee90
5f4eb0bd0fd7e0990b91bac62c6b4e879590ef71
0aabf4b6da90aa78fefabd23c8ba58d4c4e467bf

**Comment by jonasjaguar** [comment]
Mentioned commits fixed all occurrences of `malloc()`, closing
